### PR TITLE
Enabled CD

### PR DESCRIPTION
**Pull request by vwagh-dev**
### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by strangelookingnerd — CHANGES_REQUESTED** [review]
Right now the plugin already uses [renovate](https://github.com/jenkinsci/apache-httpcomponents-client-5-api-plugin/blob/21793f30520c95167a45d04093cee20f8ebae32f/.github/renovate.json) to handle dependency updates. So there is no need to use dependabot as well.

Further I would prefer to not have automated releases and opt-out of [JEP-229](https://github.com/jenkinsci/jep/blob/master/jep/229/README.adoc). 
~~It would remove the ability to have a semantic version for this plugin which is useful as [it is connected to the version](https://github.com/jenkinsci/apache-httpcomponents-client-5-api-plugin?tab=readme-ov-file#versioning) of the bundled `httpclient5` lib.~~

**Comment by jtnord** [comment]
> It would remove the ability to have a semantic version for this plugin which is useful as [it is connected to the version](https://github.com/jenkinsci/apache-httpcomponents-client-5-api-plugin?tab=readme-ov-file#versioning) of the bundled `httpclient5` lib.

this is not the case - and this is retained in the PR - the revision is specifically the version of the library - everything else comes after as a qualifier so semver is retained.

for an example see the [caffeine-api plugin](https://github.com/jenkinsci/caffeine-api-plugin/releases)

**Review by strangelookingnerd — APPROVED** [review]

**Comment by strangelookingnerd** [comment]
Waiting for https://github.com/jenkins-infra/repository-permissions-updater/pull/3980 to be merged.

**Comment by jtnord** [comment]
> > It would remove the ability to have a semantic version for this plugin which is useful as [it is connected to the version](https://github.com/jenkinsci/apache-httpcomponents-client-5-api-plugin?tab=readme-ov-file#versioning) of the bundled `httpclient5` lib.
> 
> this is not the case - and this is retained in the PR - the revision is specifically still tied to the version of the library - everything else comes after as a qualifier so semver is retained, which is exactly the same as the current release versions.

To avoid any confusion, this is not the case with how CD is implemented **here**, as it is following `Versioning with wrapped components (optional)` from [the docs](https://www.jenkins.io/doc/developer/publishing/releasing-cd/#update-maven-pom-and-config)

if you are enabling / reviewing CD on other repos, you need to follow this path, otherwise you will get non semver versions for api plugins.

**Comment by strangelookingnerd** [comment]
> > > It would remove the ability to have a semantic version for this plugin which is useful as [it is connected to the version](https://github.com/jenkinsci/apache-httpcomponents-client-5-api-plugin?tab=readme-ov-file#versioning) of the bundled `httpclient5` lib.
> > 
> > 
> > this is not the case - and this is retained in the PR - the revision is specifically still tied to the version of the library - everything else comes after as a qualifier so semver is retained, which is exactly the same as the current release versions.
> 
> To avoid any confusion, loosing semver is not the case with how CD is implemented **here**, as it is following `Versioning with wrapped components (optional)` from [the docs](https://www.jenkins.io/doc/developer/publishing/releasing-cd/#update-maven-pom-and-config)
> 
> if you are enabling / reviewing CD on other repos, you need to follow this path, otherwise you will get non semver versions for api plugins.
> 
> You can always check by running `mvn validate -Dset.changelist -Dignore.dirt` and seeing what version it creates.

Thanks for the clarification, it’s been a while since I looked at that topic. It indeed makes life easier for library plugins.

**Pull request merged**
